name: JPetStore - Original

on:
  workflow_dispatch:

jobs:
  jpetstore:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build WAR File
        shell: cmd
        run: mvnw.cmd clean package

      - name: Start Tomcat Server with Cargo Plugin
        shell: powershell
        run: |
          mvnw cargo:run -P tomcat9
          Write-Output "Verifying application availability at http://localhost:8080/jpetstore/"
