name: JPetStore - Original

on:
  workflow_dispatch:

jobs:
  jpetstore:
    runs-on: self-hosted

    steps:
      #- name: Checkout Repository
       # uses: actions/checkout@v4

     # - name: Set Up JDK 17
     #   uses: actions/setup-java@v4
     #   with:
     #     distribution: temurin
     #     java-version: 17

    #  - name: Build WAR File
    #    shell: cmd
    #    run: mvnw.cmd clean package

      - name: Start Tomcat Server with Cargo Plugin
        shell: powershell
        run: |
          Write-Output "Starting Tomcat using Cargo plugin..."
          Write-Output "Current working directory: $(Get-Location)"
          .\mvnw cargo:run -P tomcat9
