name: JPetStore - Original

on:
  workflow_dispatch:

jobs:
  jpetstore:
    runs-on: self-hosted

    steps:
      #- name: Checkout Repository
       # uses: actions/checkout@v4

     # - name: Set Up JDK 17
     #   uses: actions/setup-java@v4
     #   with:
     #     distribution: temurin
     #     java-version: 17

    #  - name: Build WAR File
    #    shell: cmd
    #    run: mvnw.cmd clean package

      - name: Start Tomcat Server with Cargo Plugin
        shell: powershell
        run: |
          Write-Output "Starting Tomcat using Cargo plugin..."
          # Start the server in the background and capture its process object.
          $proc = Start-Process -FilePath .\mvnw.cmd -ArgumentList "cargo:run", "-P", "tomcat9" -PassThru
          # Save the process ID to a file so it can be terminated later.
          $proc.Id | Out-File -FilePath cargo.pid
          Write-Output "Tomcat started with Process Id: $($proc.Id)"
          Write-Output "Verifying application availability at http://localhost:8080/jpetstore/"
